### ISSUE TITLE
Why do not use the dart to Lua ?

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#104]
Can convert dart to Lua instead of typescript?

**Comment by chgibb** [comment]
That would definitely be possible.

**Comment by weinixuehao** [comment]
@chgibb 
Do you have any idea or related documentation to do it?

**Comment by chgibb** [comment]
I don't think anyone has written a Dart to Lua compiler before. What kind of documentation are you looking for?

**Comment by weinixuehao** [comment]
@chgibb I have googled a lot, but no idea about it.

**Comment by chgibb** [comment]
https://github.com/hydro-sdk/hydro-sdk/tree/master/lib/swid doesn't quite do what you're asking but might be good inspiration.
