### ISSUE TITLE
How to debug the typescript code step by step

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#139]
Currently, The only console.log can be used?

**Comment by chgibb** [comment]
There's no direct debugger support. See https://github.com/hydro-sdk/hydro_demo for documentation on debugging.

**Comment by weinixuehao** [comment]
It only be debugged for dart not for ts?

**Comment by chgibb** [comment]
Correct. You'll need to start the Dart debugger first.

**Comment by weinixuehao** [comment]
I`m sorry to do not understand what do you meaning? Can debug step by step in typescript?

**Comment by chgibb** [comment]
No. There's no direct debugging support for Typescript code running in Hydro.

**Comment by weinixuehao** [comment]
@chgibb This feature will be added in the future?

**Comment by chgibb** [comment]
Probably eventually. There's nothing technically stopping this from happening.

**Comment by weinixuehao** [comment]
@chgibb What do you mean?

**Comment by chgibb** [comment]
There's no big technical blocker why this couldn't happen. It would just be a lot of work.
