### ISSUE TITLE
npm instal so slow

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#148]
npm install --save chgibb/hydro-sdk is so slow how to install via local? I can only install with npm i @hydro-sdk/hydro-sdk but run flutter pub get with the follow error.
```
Because every version of hydro_sdk from path depends on waveform from path which is forbidden, hydro_sdk from path is forbidden.
So, because dynamic_example depends on hydro_sdk from path, version solving failed.

pub get failed (66; So, because dynamic_example depends on hydro_sdk from path, version solving failed.)
exit code 66
```
![image](https://user-images.githubusercontent.com/17869361/100996870-9075c000-3594-11eb-9924-838f267a9314.png)

**Comment by weinixuehao** [comment]
I finally change 
```
waveform:
    path:
      node_modules/@hydro-sdk/waveform
```
to 
waveform:
    path:
      ../waveform
to fix above error
Since i run flutter pub get --verbose to view error in details which show the waveform do not exist.

**Comment by weinixuehao** [comment]
Running `node node_modules/hydro-sdk/dist/compiler -t ota/hello-world.ts -m hello-world -d assets -p debug` not working due to the package scope issue.
I suspect the latest code not working due to `scoped packages` as you change `"name": "hydro-sdk"` to `"name": "@hydro-sdk/hydro-sdk"` in the package.json

I have to change to `node node_modules/@hydro-sdk/hydro-sdk/dist/compiler -t cloud_apps/one/hello-world.ts -m hello-world -d assets -p debug -w cloud_apps/one` but still has an below error

```
/bin/sh: undefined: command not found
(node:43207) UnhandledPromiseRejectionWarning: Error: Command failed: undefined  -o assets/hello-world.hc .hydroc/19dde6181b306e53be7cb1a00ac25b3508109aa8712b53db670bd37886dffd3e/hello-world
/bin/sh: undefined: command not found

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.compileByteCodeAndWriteHash (/Users/user/Ctsmed/hydro-demo/dynamic_example/node_modules/@hydro-sdk/hydro-sdk/dist/compiler/src/compileByteCodeAndWriteHash.js:9:8)
    at Object.<anonymous> (/Users/user/Ctsmed/hydro-demo/dynamic_example/node_modules/@hydro-sdk/hydro-sdk/dist/compiler/src/buildTs.js:92:51)
    at step (/Users/user/Ctsmed/hydro-demo/dynamic_example/node_modules/@hydro-sdk/hydro-sdk/dist/compiler/src/buildTs.js:33:23)
    at Object.next (/Users/user/Ctsmed/hydro-demo/dynamic_example/node_modules/@hydro-sdk/hydro-sdk/dist/compiler/src/buildTs.js:14:53)
    at fulfilled (/Users/user/Ctsmed/hydro-demo/dynamic_example/node_modules/@hydro-sdk/hydro-sdk/dist/compiler/src/buildTs.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:43207) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was)
(node:43207) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by chgibb** [comment]
I'm working on automating the release process for hydro-sdk and bringing some other repositories online. The latest revision on `master` branch as well as the latest nightlies on NPM are currently broken for consumers. If you pin your version back to the version used by the demo projects that should work until the new publishing process is in place https://github.com/hydro-sdk/hydro_demo/pull/9

**Comment by weinixuehao** [comment]
Which commit or branch to back? The demo project using` npm install chgibb/hydro-sdk `that I can not install @chgibb

**Comment by chgibb** [comment]
@weinixuehao please see the latest readme in the demo project https://github.com/hydro-sdk/hydro_demo
Hydro now publishes a much smaller package onto `npm`. The other issues you flagged with respect to package name and paths are fixed as well.

**Comment by weinixuehao** [comment]
@chgibb 
Thanks! it fixed.

**Comment by chgibb** [comment]
Good to hear!
