### ISSUE TITLE
How to navigate another hc?

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#165]
I want to open another hc in current hc and back?
1、One hc navigate to another hc?
2、Flutter native screen A->B->C via` navigator.push()` in dart, then to load a hc file by `RunFromNetwork() `function in the C screen, How to back to B or pop in the TypeScript directly(hc file)?

```
  namespaceTable["pop"] = makeLuaDartFunc(func: (List<dynamic> args) {
    BuildContext context = maybeUnBoxAndBuildArgument<BuildContext>(args[0],
        parentState: hydroState);
    Navigator.pop(context);
    return [];
  });
```
I had used the above code to test and a black screen appears to me.

![image](https://user-images.githubusercontent.com/17869361/101569562-add0e100-3a0f-11eb-95df-010f3665478c.png)

Why do not have a pop function in navigator.ts?
```
import {BuildContext} from "../buildContext";

declare const flutter: {
    widgets: {
        navigatorPush: (this: void, context: BuildContext, route: any) => void;
    };
};

export class Navigator 
{
    public static push(context: BuildContext, route: any): void 
    {
        flutter.widgets.navigatorPush(context,route);
    }
}
```

**Comment by weinixuehao** [comment]
@chgibb 
Finally, locate the black screen issue is that having multiple MaterialApp in my project, But why do not have a pop function in navigator.ts? So I have to add this by myself.

**Comment by chgibb** [comment]
Once swid is more mature, Navigator will be rewritten to have a pop method.
