### ISSUE TITLE
How transfer params between hc?

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#170]
@chgibb 
How to return data when back to the previous screen in the following cases?
1、The previous screen is created by typescript?
2、The previous screen is created by dart?
Suppose the current screen in both cases is created by typescript?

**Comment by chgibb** [comment]
Currently none of what you described is possible. It will be possible in the future.

**Comment by weinixuehao** [comment]
@chgibb Is it possible to pass an argument to hc from dart? hostArgs?

**Comment by chgibb** [comment]
That's correct.
