### ISSUE TITLE
About await and async

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#179]
@chgibb 
How to async program with `hydro-sdk`?
Has the other solution to instead of the await and async, only `Future`?

**The reason why they have not been supporting is the `typescripttolua` has not this feature?**

**Comment by chgibb** [comment]
That's correct. It might be possible in the future to port Typescript's async/await down leveling transformation for ES5 to produce code that leverages Dart `Future`s and `Completer`s to achieve the same effect.
