### ISSUE TITLE
How to get the type of a generic callback

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#184]
in typescript 
`export type callback<T> = (this: void) => T | undefined;`

The `callback` represented as a `Closure` in dart, but how to know the type of `T`?

**Comment by chgibb** [comment]
Typescript generics are wholly erased so this is not possible. You could attempt a pattern similar to what Hydro's `ScopedModel` implementation does by requiring arguments that contain runtime types .
https://github.com/hydro-sdk/hydro-sdk/blob/master/runtime/scopedModel/scopedModel.ts

**Comment by weinixuehao** [comment]
@chgibb My idea is how to gracefully map a generic class, e.g removing the if ... else ... statements in dart. 

```
  table["resolveWith"] = makeLuaDartFunc(func: (List<dynamic> args) {
    String displayName = args[1]["displayName"];
    if (displayName == "Color") {
      return [
        MaterialStateProperty.resolveWith<Color>((states) {
          Closure closure = args[0];
          final setBox = maybeBoxObject<Set>(
              object: states, hydroState: luaState, table: table);
          List<dynamic> ret = closure.dispatch([setBox], parentState: luaState);
          Color color =
              maybeUnBoxAndBuildArgument<Color>(ret[0], parentState: luaState);
          return color;
        })
      ];
    } else if (displayName == "TextStyle") {
      return [
        MaterialStateProperty.resolveWith<TextStyle>((states) {
          Closure closure = args[0];
          final setBox = maybeBoxObject<Set>(
              object: states, hydroState: luaState, table: table);
          List<dynamic> ret = closure.dispatch([setBox], parentState: luaState);
          TextStyle textStyle =
              maybeUnBoxAndBuildArgument<TextStyle>(ret[0], parentState: luaState);
          return textStyle;
        })
      ];
    }
```
The generic type must be explicitly specified. e.g Color、TextStyle. So here must use` if else statement`, Have a more graceful solution?

**Comment by chgibb** [comment]
At the moment, no there isn't really another solution. This is a good pattern though. Something similar is used already for `AlwaysStoppedAnimation`. I think this should be supported by the binding generator eventually with some configurable constraints if they're known ahead of time as they are here.
