### ISSUE TITLE
The pcall function consumed a lot of time

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#190]
The `pcall` function consumed a lot of time as the byte code larger and larger.

![image](https://user-images.githubusercontent.com/17869361/103083655-df54c980-4617-11eb-974a-16d336b04f5e.png)

in hotReloadable.dart
```
      setState(() {
        func = val;
        int startTime = DateTime.now().second;
        res = func.pcall([], parentState: luaState);
        print("measured time:${DateTime.now().second - startTime}");
      });

✓ Built build/app/outputs/flutter-apk/app-profile.apk (10.8MB).
Connecting to VM Service at ws://127.0.0.1:59804/6ldpYJ8MuVA=/ws
I/flutter ( 2242): I/Hydro 0 native, 760 virtual prototypes
I/flutter ( 2242): measured time:16
```
@chgibb 
How to optimize it?

**Comment by chgibb** [comment]
Is the code you're seeing this in open source? Could I see it? Are you building with `-p debug` or `-p release`? How large are the `.hc` and `.hc.symbols` files?

**Comment by weinixuehao** [comment]
[debug.zip](https://github.com/hydro-sdk/hydro-sdk/files/5740786/debug.zip)
[release.zip](https://github.com/hydro-sdk/hydro-sdk/files/5740791/release.zip)
[lua.txt](https://github.com/hydro-sdk/hydro-sdk/files/5740798/lua.txt)

The above evaluates are in profile mode, The bytecode was built in release mode.
@chgibb

**Comment by chgibb** [comment]
I think building all code from `node_modules` into a separate `vendor.hc` file or something during development is a good idea. It would help to alleviate the issues you're seeing here. It would require some major changes to the toolchain as well as the VM and would probably be specific to the current Typescript toolchain.

In the meantime, I've had a look at the attached `lua.txt` file. It looks like you're using barrel imports like `runtime/flutter/material/index`. Importing only what you're actually using in each file like:
```typescript
import {Appbar} from "runtime/flutter/material/appBar";
import {Card} from "runtime/flutter/material/card";
```
instead of:
```
import {Appbar, Card} from "runtime/flutter/material/index":
```
should alleviate a lot of the slowness when hot reloading that you're seeing.

**Comment by weinixuehao** [comment]
`import {Appbar} from "runtime/flutter/material/appBar";`
Yes, I realized above too, But it will be sooner or later to import these as the project grows. 
I have developed my company project with hydro-sdk, so it is important for me to fix this issue soon. 

`I think building all code from node_modules into a separate vendor.hc file or something during development is a good idea. It would help to alleviate the issues you're seeing here. It would require some major changes to the toolchain as well as the VM and would probably be specific to the current Typescript toolchain.`
Could you give me some ideas? 

The `vendor.hc` be loaded at app launch time to generate a `luaState`. We can think of it as a necessary system service to serve the system api to the` customer.hc`? Multiple `customer.hc` share the system service?  It feels like a mini operating system? This may need a large work to do it. Is this what you meaning?

**Comment by chgibb** [comment]
> Yes, I realized above too, But it will be sooner or later to import these as the project grows.

It's not a permanent solution but it does eliminate the overhead from barrel imports. The barrel import for `flutter/material` for example looks like the following:
```lua
package.preload["runtime.flutter.material.index"] = (function (...)
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
do
    local ____export = require("runtime.flutter.material.appBar")
    for ____exportKey, ____exportValue in pairs(____export) do
        ____exports[____exportKey] = ____exportValue
    end
end
do
    local ____export = require("runtime.flutter.material.flatButton")
    for ____exportKey, ____exportValue in pairs(____export) do
        ____exports[____exportKey] = ____exportValue
    end
end
do
    local ____export = require("runtime.flutter.material.circularProgressIndicator")
    for ____exportKey, ____exportValue in pairs(____export) do
        ____exports[____exportKey] = ____exportValue
    end
end
do
    local ____export = require("runtime.flutter.material.stretchMode")
    for ____exportKey, ____exportValue in pairs(____export) do
        ____exports[____exportKey] = ____exportValue
    end
end
```
and so on, for every single file under `flutter/material`. Removing all barrel imports removes all of this extra overhead.

You could also try compiling your `.hc` files to Dart. The program `hc2Dart.dart` under `bin/` will take your `.hc` files and produce an `hc.g.dart` file in your `lib` folder. You can then pass the `thunks` variable from `hc.g.dart` to `RunFromNetwork` to replace at least some Lua functions with Dart ones. This should help speed up hot reload as well. Any functions you don't change while developing will run in pure Dart instead of Lua.

> I have developed my company project with hydro-sdk, so it is important for me to fix this issue soon.  

I don't recommend anyone build anything for production use with Hydro-SDK at this stage of it's development. Not until it's stable enough for a version `1.0.0` release at least.

>  It is possible to implement the VM in C/C++. In fact, it is a process of loop and recursion for making a luaState? please give me an explanation in detail to do it.

Hydro-SDK relies on Dart's reified type system to allow for rich Lua<->Dart bindings. It also relies on Dart's GC for memory management. Rewriting the VM in C++ is probably possible but would require a lot of work.

**Comment by weinixuehao** [comment]
1、barrel import? how to write in ts? which tag(version) in the repo?
2、I have no other better solution for production, so I must fix this issue.
3、The `fullRestart` function will be invoked multiple times. In fact, it only needs one time to make luaState.

**Comment by weinixuehao** [comment]
![image](https://user-images.githubusercontent.com/17869361/103251803-5e018c00-49b5-11eb-8c52-069291a68b38.png)
Is _G Infinite recursion?

**Comment by weinixuehao** [comment]
I found the performance is not related to hydro-sdk, I did a test with the following code.

```
import { MaterialApp, Scaffold } from "../../runtime/flutter/material/index";
import { runApp } from "../../runtime/flutter/runApp";
import { Text } from "../../runtime/flutter/widgets/index";
import { CupertinoApp } from "../../runtime/flutter/cupertino/index";
import { Alignment } from "../../runtime/flutter/painting/index";
import { SmartQuotesType } from "../../runtime/flutter/services/index";
import { Key } from "../../runtime/flutter/foundation/index";
import { MainAxisAlignment } from "../../runtime/flutter/rendering/index";
import { Widget } from "../../runtime/flutter/widget";

const i = 1+2;
```

measure time as the following
```
flutter: I/Hydro 0 native, 717 virtual prototypes
flutter: elapsed time:0:00:00.011053
```

**Comment by weinixuehao** [comment]
HydroTable is not efficient enough, The `rawset` cost 60ms once time.
![image](https://user-images.githubusercontent.com/17869361/103261379-599c9980-49dc-11eb-8991-07c9706da3ae.png)

**Comment by weinixuehao** [comment]
```
preload[.........]
preload[.........]
preload[.........]
preload[.........]
preload[.........]
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
require("lualib_bundle");
local ____exports = {}
local ____materialApp = require("runtime.flutter.material.materialApp")
local MaterialApp = ____materialApp.MaterialApp
local ____runApp = require("runtime.flutter.runApp")
local runApp = ____runApp.runApp
local ____index = require("runtime.flutter.widgets.index")
local Text = ____index.Text
runApp(
    function() return __TS__New(
        MaterialApp,
        {
            home = __TS__New(Text, "123123")
        }
    ) end
)
return ____exports
```
The `preload` does not cost much time. The key is in `require(.......)`

**Comment by weinixuehao** [comment]
I had tried a test for my idea, it indeed reduces the call time of `pcall`.
After: cost time=0:00:07.034042
Befor: cost time=0:00:13.035285

**Comment by weinixuehao** [comment]
I had changed bundlePrelude.ts to the following
// export const bundlePrelude = `
// local package = {preload={}}
// local function require(file)
//     return package.preload[file]()
// end\n`;

```
export const bundlePrelude = `
local package = {preload={}, loaded={}}
local function require(file)
    local loadedModule = package.loaded[file]
    if loadedModule == nil
    then
        loadedModule = package.preload[file]()
        package.loaded[file] = loadedModule
        return loadedModule
    end
    return loadedModule
end\n`;
```

**Comment by chgibb** [comment]
@weinixuehao 
>1、barrel import? how to write in ts? which tag(version) in the repo?  

I was advocating for not using barrel imports.

>3、The fullRestart function will be invoked multiple times. In fact, it only needs one time to make luaState.

I'm not sure why this is the case. Good to know though.

>4、The hc.g.dart could not be placed to remote for downloading?

It's compiled into your app with the rest of your Dart code.

>I had changed bundlePrelude.ts to the following
>Before
>
>`export const bundlePrelude = 
>local package = {preload={}}
>local function require(file)
>     return package.preload[file]()
>end\n`;
>After
>
>`export const bundlePrelude = 
>local package = {preload={}, loaded={}}
>local function require(file)
>    local loadedModule = package.loaded[file]
>    if loadedModule == nil
>    then
>        loadedModule = package.preload[file]()
>        package.loaded[file] = loadedModule
>        return loadedModule
>    end
>    return loadedModule
>end\n`;
>cost time=0:00:00.136853

That's amazing! Would you mind opening a PR with this change please?

**Comment by weinixuehao** [comment]
@chgibb 
I am sorry, I can not open PR for this issue as my code had been changed a lot. so maybe you need to add by yourself.

**Comment by chgibb** [comment]
@weinixuehao sorry for the delay. Your suggested fix has landed so I'm going to close this issue.
