### ISSUE TITLE
PlatformView Support Issues

### ISSUE THREAD

**Issue by NoahHahm** [hydro-sdk/hydro-sdk#587]
The default flutter supports PlatformView, but there seems to be no related code even if I search the hydro-sdk internal code.
In real production environments, you will often need to use a native PlatformView . (ex. WebView, SurfaceView...)
(because of the lack of functional environment of Flutter)
do you have any support plans?

**Comment by chgibb** [comment]
Eventually, all of Dart, Flutter and third-party packages will be supported by automatic binding generation (https://hydro-sdk.io/docs/design-documents/swid). I'm currently working on support for `dart:ui` (which can be tracked here https://github.com/hydro-sdk/hydro-sdk/projects/17).

While PlatformView currently is not supported, bindings for it can be hand written either in Hydro-SDK itself or in your code. There's some documentation about that here https://github.com/hydro-sdk/hydro-sdk/blob/master/bindings.md . Let me know if that helps. 

If that doesn't clear anything up, let me know what PlatformView classes you're interested in and I can hand write them in Hydro-SDK.

**Comment by NoahHahm** [comment]
thanks for the link to the relevant documentation. I think you should get used to the hydro-sdk internal structure.
