### ISSUE TITLE
Inquiries related to some dart native widgets

### ISSUE THREAD

**Issue by NoahHahm** [hydro-sdk/hydro-sdk#592]
when composing UI through hydro-sdk, is it possible to mix configuration with some dart widget native code? I think there is a need to use other dart UI libraries or unmapped UIs.
are there any examples written about it?
should I configure the widgets 100% via hydro-sdk?
does it mean to configure a part of the app like the introduction of the site, or to attach a widget composed of hydro in Dart? Are you saying that you are configuring some entire UI through hydro?
for example... on a platform view that has not yet been mapped.
I want to append a widget configured through hydro
````
Write parts of your app, or even your entire app with Hydro-SDK. It's all widgets
````

**Comment by NoahHahm** [comment]
I checked that it is available through RunComponent.

**Comment by chgibb** [comment]
Hi @NoahHahm there's some examples of hand writing bindings [here](https://github.com/hydro-sdk/hydro-sdk/blob/master/test/widget/customWidget-1_test.dart) and [here](https://github.com/hydro-sdk/hydro-sdk/blob/master/test/widget/customWidget-1.ts). Is this what you're looking to do?

**Comment by NoahHahm** [comment]
The test was completed to put the ota widget as a child widget in the dart code.
Conversely, I was curious how to put a widget developed in Dart in ts.

**Comment by chgibb** [comment]
The links I sent above are an example of how to expose a widget written in Dart to Typescript.
