### ISSUE TITLE
How to use RunFromBundle?

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#77]
```
import 'package:flutter/material.dart';
import 'package:hydro_sdk/hc.g.dart';
import 'package:hydro_sdk/runFromBundle.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(RunFromBundle(args: [], thunks: thunks, path: "assets/hello-world.hc"));
}
```

it crash with the following exception:
![image](https://user-images.githubusercontent.com/17869361/99044201-58e5aa80-25ca-11eb-839b-f7b470f7b37f.png)

**Comment by chgibb** [comment]
Hi @weinixuehao , thanks for checking out Hydro! There's been a lot of changes to the way Hydro deals with hot reload and source maps in the last 6 months. `RunFromBundle` wasn't kept up to date with the changes. It should be fixed on the `master` branch now.

**Comment by weinixuehao** [comment]
@chgibb Thanks for open-source this project which is an awesome project! I will use it in my project so I have a concern that the project will keep updating in the future?

**Comment by chgibb** [comment]
@weinixuehao it's been around for almost a year and a half now. It will definitely keep getting updated in the future! The current focus is on tools to automatically generate Typescript+Dart code from Dart packages to make exposing more of Flutter and third-party packages easier.
