### ISSUE TITLE
How to use hot-reload

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#79]
I compiled with node node_modules/hydro-sdk/dist/compiler -t hello_world.ts -m hello-world -d assets -p debug -w hello-world.ts but when changed the file again with cmd+s(vs-code) to save, The app keeps the same without any change. I launch a web server with https://www.npmjs.com/package/local-web-server which enable me to download file with 127.0.0.1:5000 in debug mode.  If I did something wrong please point out, thank you very much!

**Comment by weinixuehao** [comment]
I have seen the compiler source code which launches a server with port 5000 when to compile but still unable to hot-load.

**Comment by chgibb** [comment]
Could you show me your `main.dart`?

**Comment by weinixuehao** [comment]
Sorry, I am asking a question here without a thorough understanding. It is actually working, I have seen this compiler source code. But the documentation is not clear and when I change something in the file which is listening cause all file rebuilding, It is so slow.

**Comment by chgibb** [comment]
That's weird that's causing a full rebuild. Do you have a repository I could look at where it's doing this?

**Comment by chgibb** [comment]
@weinixuehao this issue should be fixed. Please see updated example project at https://github.com/hydro-sdk/hydro_demo
