### ISSUE TITLE
Showing text in Chinese is unreadable code

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#80]
![image](https://user-images.githubusercontent.com/17869361/99379394-94061780-2903-11eb-937f-a63631147631.png)
Both Android and Ios is the same issue.

**Comment by weinixuehao** [comment]
The unreadable String is produced here.
![image](https://user-images.githubusercontent.com/17869361/99401942-bb6cdc80-2923-11eb-80cb-3901002e58e3.png)

**Comment by chgibb** [comment]
Could you comment the Chinese text you're using here so I can try to make a test case out of it please? I'm fairly certain this is a limitation of `luac` 5.2 which the Hydro compiler uses as the last step to actually compile your Typescript code into bytecode that is served to a running VM. It might be possible to either upgrade to `luac` 5.3, or to create a compiler pass to escape unicode characters before passing the code to `luac`.

**Comment by weinixuehao** [comment]
@chgibb 
`   public build(): Widget {
        console.log(this.controller.getText().toLowerCase());
        return new MaterialApp({
            home: new Scaffold({
                backgroundColor: Colors.blueGrey.swatch[50],
                body: new SafeArea({
                    child: ListView.builder({
                        itemCount: 10000,
                        itemBuilder: (context: BuildContext, index: number) => {
                            return new Container({
                                child: new Text(
                                    `测试性能` + index
                                )
                            });
                        }
                    })
                })
            })
        });
    }
}`

The `测试性能` is the Chinese text

**Comment by weinixuehao** [comment]
```
  String readString() {
    var uint8list = read(readInt(code.ptrSize, code.bigEndian) - 1);
        // String o = new String.fromCharCodes(
        //     uint8list);
    String o = Utf8Decoder().convert(uint8list);
    if (read(1)[0] != 0) throw "Corrupt string";
    return o;
  }
```
The Chinese text is showing as expect with Changing `fromCharCodes` to `Utf8Decoder().convert(uint8list)`

**Comment by chgibb** [comment]
That's much easier than building a Unicode compiler pass! Thanks for digging into this. Would you mind opening a PR with this fix?

**Comment by weinixuehao** [comment]
@chgibb 
I hope you to synchronize this code to the master branch to fix this, I do not want to fork for my project.

**Comment by chgibb** [comment]
@weinixuehao this should be fixed in 0.0.1-nightly.24 which will be live in a few minutes.

**Comment by weinixuehao** [comment]
@chgibb Thanks! Could you add a git tag for each stable version?

**Comment by chgibb** [comment]
@weinixuehao I think it's still too early to commit to anything being "stable" per se. That being said, there is a git tag for every single release including nightlies.
