### ISSUE TITLE
Data transfer question

### ISSUE THREAD

**Issue by fatkullinalina** [hydro-sdk/hydro-sdk#81]
Hi. I have question about data transfer between apps. Is there any easy ways  to transfer data from app that we run with RunFromNetwork to main flutter app?

**Comment by chgibb** [comment]
Hi @fatkullinalina thanks for checking out Hydro! What you're describing should be possible by passing a callback through as an argument to `RunFromNetwork`. Check out the host arguments example for inspiration:
https://github.com/chgibb/hydro-sdk/blob/master/examples/hostArgs/index.ts
https://github.com/chgibb/hydro-sdk/blob/master/test/smoke/host-args_test.dart

Let me know if you still need assistance.

**Comment by fatkullinalina** [comment]
Thank you for answer. I've tries to pass function as an argument to RunFromNetwork. But it can't call it.
import { runApp } from "hydro-sdk/runtime/flutter/runApp";
//Make sure to import from /index specifically if using barell imports.
import {TextFormField} from "hydro-sdk/runtime/flutter/material/textFormField";
//The compiler won't resolve /index by itself
import {
    StatelessWidget,
    Text,
    Container,
    TextEditingController
} from "hydro-sdk/runtime/flutter/widgets/index";
import { MaterialApp } from "hydro-sdk/runtime/flutter/material/index";
import { Widget } from "hydro-sdk/runtime/flutter/widget";
import { Key } from "hydro-sdk/runtime/flutter/foundation/key";

class MyWidget extends StatelessWidget {
    private controller = new TextEditingController({ text: "Some convoluted but familiar functions" });
    private title:string;
    private myfunction:()=>void;
    public constructor(title:string,myfunction:()=>void) {
        super();
        this.title=title;
        this.myfunction=myfunction;

    }

    public build(): Widget {
        console.log(this.controller.getText().toLowerCase());
        return new MaterialApp({
            home: new Container({
                key: new Key(this.controller.getText().toLowerCase()),
                child: new TextFormField({
                    onChanged: (val) => 
                    {
                       this.myfunction();
                    }
                })
            })
        });
    }
}

runApp((title:string,myfunction:()=>void) => new MyWidget(title,myfunction));


 void myfunction() {
    setState(() {
      count += 1;
    });
    
  }

onPressed: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) => RunFromNetwork(
                                        thunks: thunks,
                                        args: ['alina', myfunction],
                                        baseUrl:
                                            "https://github.com/fatkullinalina/hydra/raw/main",
                                        filePath: "hello-world.hc",
                                      )),
                            );
                          }),


![Безымянный](https://user-images.githubusercontent.com/48031857/99785904-de1f1100-2b2e-11eb-9790-a422b980932a.png)

**Comment by chgibb** [comment]
@fatkullinalina the function you pass in will need to follow the rules mentioned under "Binding Dart Code to Guest Code" in the readme.
