### ISSUE TITLE
The http only support get request? 

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#82]
How to send a request by post? Do I need to add a post request myself or waiting for you?

**Comment by chgibb** [comment]
At the moment, the only projection for `http` is `get`. If you want to open a PR to add `post` or others I would be more than happy to accept it.

**Comment by weinixuehao** [comment]
Thank you! I want to add this by myself but worry about changing this code does not synchronize with you. Do you have any ideas?

**Comment by chgibb** [comment]
What do you mean?

**Comment by weinixuehao** [comment]
@chgibb 
If I need to add a custom widget in here as the following image
![Uploading image.png…]()

And this file may be changed in the future for some reason, For example, the new version of the Flutter SDK delivers some new widget and you need to extend them into the hydro-sdk or others, So we all modified this file, I want to maintain a separate branch, but I want to keep in sync with your future code changes

**Comment by weinixuehao** [comment]
@chgibb This can be accomplished with custom Namespaces, I am sorry to submit this issue.

**Comment by chgibb** [comment]
No worries.
