### ISSUE TITLE
Provide info on the current supported version of flutter.

### ISSUE THREAD

**Issue by wardourdigital** [hydro-sdk/hydro-sdk#831]
Hi there,

I have been trying to run this project on a simple counter app but I encounter an error in the Xcode build. I can already see some comment about supporting some versions of Flutter 2.2 and 2.8 while I had tried on 2.15.

What is the lowest version supported?

Thanks

**Comment by soahyle** [comment]
@wardourdigital, it's 2.0.6 according to the [Github Actions](https://github.com/hydro-sdk/hydro-sdk/blob/master/.github/workflows/swid-tests-.yml). He's currently working on [this branch](https://github.com/hydro-sdk/hydro-sdk/tree/swid-flutter) to support Flutter 2.8.

**Comment by wardourdigital** [comment]
Awesome. Thank you.
